create table person
(
    id   int PRIMARY KEY,
    name varchar(100),
    age  int
);
insert into person
values (1, 'Artem', 21);
drop table person;
create table person
(
    id   int generated by default as identity primary key,
    name varchar,
    age  int
);
select *
from person;


create table person
(
    id   int generated by default as identity primary key,
    name varchar(100) not null,
    age  int check (age < 100)
);
create table item
(
    id        int generated by default as identity primary key,
    person_id int          references person (id) on delete set null,
    item_name varchar(100) not null
);

insert into person(name, age)
values ('Tom', 35),
       ('Bob', 52),
       ('Katy', 14);
select *
from item;
insert into item(person_id, item_name)
values (1, 'Book'),
       (1, 'Airpods'),
       (2, 'Iphone'),
       (3, 'Mp3'),
       (3, 'Kindle'),
       (3, 'Tv'),
       (3, 'PS5');

Drop table actor_movie cascade;

CREATE table person
(
    id   int generated by default as identity primary key,
    name varchar(100) not null,
    age  int
);
create table passport
(
    id              int generated by default as identity primary key,
    passport_number int not null,
    person_id       int unique references person (id) on delete cascade
);

create table actor
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique,
    age  int check ( age > 0 )
);
create table movie
(
    id                 int generated by default as identity primary key,
    name               varchar(200) not null,
    year_of_production int check ( year_of_production > 1900 )
);
create table actor_movie
(
    id       int references actor (id),
    movie_id int references movie (id),
    primary key (id, movie_id)
);


